require:
  - rubocop-performance
  - rubocop-rspec
  - rubocop-rails

AllCops:
  TargetRubyVersion: 2.6.5
  Exclude:
    - db/schema.rb
    - bin/bundle

Layout/LineLength:
  Max: 120

Style/Documentation:
  Enabled: false
